### ISSUE TITLE
meson build fails

### ISSUE THREAD

**Issue by kvijay1918** [Comcast/cjwt#51]
Is that completed?
**********************

meson setup --warnlevel 3 --werror build
The Meson build system
Version: 0.61.5
Source dir: /home/isecl-ami/vijay/cjwt/cjwt
Build dir: /home/isecl-ami/vijay/cjwt/cjwt/build
Build type: native build
Project name: cjwt
Project version: 2.1.0
C compiler for the host machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C linker for the host machine: cc ld.bfd 2.30
Host machine cpu family: x86_64
Host machine cpu: x86_64
Configuring cjwtver.h using configuration
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Run-time dependency openssl found: YES 1.1.1
Run-time dependency libcjson found: YES 1.7.15
Found CMake: /usr/bin/cmake (3.10.2)
Run-time dependency trower-base64 found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency trower-base64

Executing subproject trower-base64

trower-base64| Project name: trower-base64
trower-base64| Project version: 1.2.7
trower-base64| C compiler for the host machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
trower-base64| C linker for the host machine: cc ld.bfd 2.30
trower-base64| Configuring ver.h using configuration
trower-base64| Program reuse found: NO
trower-base64| Build targets in project: 1
trower-base64| Subproject trower-base64 finished.

Dependency trower-base64 found: YES 1.2.7 (overridden)
Run-time dependency cunit found: YES 2.1-3
Program reuse found: NO
Build targets in project: 11

cjwt 2.1.0

  Subprojects
    trower-base64: YES

  User defined options
    warning_level: 3
    werror       : True

Found ninja-1.8.2 at /usr/bin/ninja
WARNING: Need gcovr or lcov/genhtml to generate any coverage reports
NOTICE: You are using Python 3.6 which is EOL. Starting with v0.62.0, Meson will require Python 3.7 or newer

**Comment by kvijay1918** [comment]
~/vijay/cjwt/cjwt/build$ ninja all test coverage
[0/2] Running all tests.
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe... 'valgrind'")>) at /usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py:1852
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe... 'valgrind'")>) at /usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py:1852>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1854, in test_done
    f.result()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1849, in run_test
    res = await test.run(self)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1393, in run
    await self._run_cmd(harness, cmd)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1451, in _run_cmd
    cwd=self.test.workdir)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1426, in _run_subprocess
    preexec_fn=preexec_fn if not is_windows() else None)
  File "/usr/lib/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1211, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 200, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib/python3.6/asyncio/base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 706, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'valgrind': 'valgrind'
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe... 'valgrind'")>) at /usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py:1852
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe... 'valgrind'")>) at /usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py:1852>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1854, in test_done
    f.result()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1849, in run_test
    res = await test.run(self)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1393, in run
    await self._run_cmd(harness, cmd)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1451, in _run_cmd
    cwd=self.test.workdir)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1426, in _run_subprocess
    preexec_fn=preexec_fn if not is_windows() else None)
  File "/usr/lib/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1211, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 200, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib/python3.6/asyncio/base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 706, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'valgrind': 'valgrind'
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe... 'valgrind'")>) at /usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py:1852
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe... 'valgrind'")>) at /usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py:1852>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1854, in test_done
    f.result()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1849, in run_test
    res = await test.run(self)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1393, in run
    await self._run_cmd(harness, cmd)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1451, in _run_cmd
    cwd=self.test.workdir)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1426, in _run_subprocess
    preexec_fn=preexec_fn if not is_windows() else None)
  File "/usr/lib/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1211, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 200, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib/python3.6/asyncio/base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 706, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'valgrind': 'valgrind'
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe... 'valgrind'")>) at /usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py:1852
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe... 'valgrind'")>) at /usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py:1852>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1854, in test_done
    f.result()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1849, in run_test
    res = await test.run(self)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1393, in run
    await self._run_cmd(harness, cmd)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1451, in _run_cmd
    cwd=self.test.workdir)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1426, in _run_subprocess
    preexec_fn=preexec_fn if not is_windows() else None)
  File "/usr/lib/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1211, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 200, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib/python3.6/asyncio/base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 706, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'valgrind': 'valgrind'
Exception in callback TestHarness._run_tests.<locals>.test_done(<Task finishe... 'valgrind'")>) at /usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py:1852
handle: <Handle TestHarness._run_tests.<locals>.test_done(<Task finishe... 'valgrind'")>) at /usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py:1852>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1854, in test_done
    f.result()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1849, in run_test
    res = await test.run(self)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1393, in run
    await self._run_cmd(harness, cmd)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1451, in _run_cmd
    cwd=self.test.workdir)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1426, in _run_subprocess
    preexec_fn=preexec_fn if not is_windows() else None)
  File "/usr/lib/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1211, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 200, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib/python3.6/asyncio/base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 706, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'valgrind': 'valgrind'


Ok:                 0
Expected Fail:      0
Fail:               0
Unexpected Pass:    0
Skipped:            0
Timeout:            0

Full log written to /home/isecl-ami/vijay/cjwt/cjwt/build/meson-logs/testlog.txt
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mesonmain.py", line 148, in run
    return options.run_func(options)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 2010, in run
    return th.doit()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1687, in doit
    self.run_tests(runners)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1826, in run_tests
    loop.run_until_complete(self._run_tests(runners))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1923, in _run_tests
    await complete_all(futures)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1193, in complete_all
    check_futures(done)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1183, in check_futures
    f.result()
  File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1854, in test_done
    f.result()
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1849, in run_test
    res = await test.run(self)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1393, in run
    await self._run_cmd(harness, cmd)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1451, in _run_cmd
    cwd=self.test.workdir)
  File "/usr/local/lib/python3.6/dist-packages/mesonbuild/mtest.py", line 1426, in _run_subprocess
    preexec_fn=preexec_fn if not is_windows() else None)
  File "/usr/lib/python3.6/asyncio/subprocess.py", line 225, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1211, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 200, in _make_subprocess_transport
    **kwargs)
  File "/usr/lib/python3.6/asyncio/base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 706, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'valgrind': 'valgrind'

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
NOTICE: You are using Python 3.6 which is EOL. Starting with v0.62.0, Meson will require Python 3.7 or newer
[0/2] Generates coverage reports
FAILED: meson-test
/usr/local/bin/meson test --no-rebuild --print-errorlogs
[2/2] Generates coverage reports
lines: 0.0% (0 out of 885)
branches: 0.0% (0 out of 509)

Xml coverage report can be found at file:///home/isecl-ami/vijay/cjwt/cjwt/build/meson-logs/coverage.xml
Text coverage report can be found at file:///home/isecl-ami/vijay/cjwt/cjwt/build/meson-logs/coverage.txt
Html coverage report can be found at file:///home/isecl-ami/vijay/cjwt/cjwt/build/meson-logs/coveragereport/index.html
ninja: build stopped: subcommand failed.
isecl-ami@ubuntu-template:~/vijay/cjwt/cjwt/build$

**Comment by kvijay1918** [comment]
it worked..!
